// AngularConsume-Api/app/add-task/add-task.component.ts
import { Component } from '@angular/core';
import { ApiTaskService } from '../api-task.service';
import { ActivatedRoute, Router } from '@angular/router';
import { FormControl, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-add-task',
  templateUrl: './add-task.component.html',
  styleUrl: './add-task.component.css'
})

export class AddTaskComponent {

  id=-1;
  btnName="Add tasks";
  constructor(private api:ApiTaskService,private router:Router,private actRou:ActivatedRoute){}
  myForm=new FormGroup({
    AssignmentId:new FormControl(''),
    ProjectId:new FormControl(''),
    AssignedTo:new FormControl(''),
    TaskDescription:new FormControl(''),
    Deadline:new FormControl(''),
   
  });
  ngOnInit(){
    if(this.actRou.snapshot.params['id']!=null){
      this.btnName="Edit Tasks";
      this.id=this.actRou.snapshot.params['id'];
      this.api.getTasksById(this.id).subscribe((res:any)=>{
        this.myForm.controls.AssignmentId.setValue(res.AssignmentId);
        this.myForm.controls.ProjectId.setValue(res.ProjectId);
        this.myForm.controls.AssignedTo.setValue(res.AssignedTo);
        this.myForm.controls.TaskDescription.setValue(res.TaskDescription);
        this.myForm.controls.Deadline.setValue(res.Deadline);
     
      });
    }
  }
  insert(){
    if(this.id>0){
      this.api.updateTasks(this.id,this.myForm.value).subscribe((res)=>{
        this.router.navigate(['/tasks']);
    });
    }
    else{
      this.api.insertTasks(this.myForm.value).subscribe((res)=>{
        this.router.navigate(['/tasks']);
        
    });
    }
  }
}

<form [formGroup]="myForm" (ngSubmit)="insert()">
    <table class="table table-hover  table-bordered border-danger " >
        <tbody>
        <tr>
            <td>Enter AssignmentId</td>
            <td>:</td>
            <td><input type="text" formControlName="AssignmentId"/></td>
        </tr>
        <tr>
            <td>Enter ProjectId</td>
            <td>:</td>
            <td><input type="text" formControlProjectId="ProjectId"/></td>
        </tr>
        <tr>
            <td>Enter AssignedTo</td>
            <td>:</td>
            <td><input type="text" formControlName="AssignedTo"/></td>
        </tr>
        <tr>
            <td>Enter TaskDescription</td>
            <td>:</td>
            <td><input type="text" formControlName="TaskDescription"/></td>
        </tr>
        <tr>
            <td>Enter Deadline</td>
            <td>:</td>
            <td><input type="text" formControlName="Deadline"/></td>
        </tr>
      
        <tr>
            <td colspan="3" style="text-align: center;"> <button class="btn btn-outline-info " [value]="btnName">Add</button></td>
           
        </tr></tbody>
    </table>
    </form>

// React_Consume-API/Components/AddTask.js
import { useState } from "react";
import { useNavigate} from "react-router-dom";

function AddTask() {
  const navigate=useNavigate();
  const[tasks,setTask]=useState({});

  return (
    <>
    <table class="table table-hover  table-bordered border-danger " >
    <tbody>

    <tr>
        <td>Enter AssignmentId:</td>
        <td>
            <input 
                value={tasks.AssignmentId}
                onChange={(e)=>{
                setTask({...tasks,AssignmentId:e.target.value});
            }} type="text" placeholder="Enter AssignmentId" />
        </td>
    </tr>
        
    <tr>
        <td>Enter ProjectId:</td>
        <td>
            <input 
                value={tasks.ProjectId}
                onChange={(e)=>{
                setTask({...tasks,ProjectId:e.target.value});
            }} type="text" placeholder="Enter ProjectId"/>
        </td>
    </tr>

    <tr>
        <td>Enter AssignedTo:</td>
        <td>
            <input 
                value={tasks.AssignedTo}
                onChange={(e)=>{
                setTask({...tasks,AssignedTo:e.target.value});
            }} type="text" placeholder="Enter AssignedTo"/>
        </td>
    </tr>

    <tr>
        <td>Enter TaskDescription:</td>
        <td>
            <input 
                value={tasks.TaskDescription}
                onChange={(e)=>{
                setTask({...tasks,TaskDescription:e.target.value});
            }} type="text" placeholder="Enter TaskDescription"/>
        </td>
    </tr>

    <tr>
        <td>Enter Deadline:</td>
        <td>
            <input 
                value={tasks.Deadline}
                onChange={(e)=>{
                setTask({...tasks,Deadline:e.target.value});
            }} type="text" placeholder="Enter Deadline"/>
        </td>
    </tr>
    </tbody>
    </table>

    <div style={{ textAlign: 'center' }}>
      <button className="btn btn-outline-info " onClick={()=>{
    
        fetch("http://localhost:3001/insert",
        {
            method:"POST",
            body:JSON.stringify(tasks),
            headers:{
                "Content-type":"application/json"
            }
        })
        .then(()=>{navigate("/getall")});
      }}>
        Add
      </button>
    </div>
    </>
  );
}
export default AddTask;
